CXX = g++
LIB = -lgtest_main -lgtest

wrong1: Wrong1.cpp
	$(CXX) -o wrong1 Wrong1.cpp

wrong2: Wrong2.cpp
	$(CXX) -o wrong2 Wrong2.cpp

wrong3: Wrong3.cpp
	$(CXX) -o wrong3 Wrong3.cpp

uninit: Uninit.cpp
	$(CXX) -o uninit Uninit.cpp

datatypes1: Datatypes1.cpp
	$(CXX) -o datatypes1 Datatypes1.cpp

datatypes2: Datatypes2.cpp
	$(CXX) -o datatypes2 Datatypes2.cpp

datatypes3: Datatypes3.cpp
	$(CXX) -o datatypes3 Datatypes3.cpp

overflow: Overflow.cpp
	$(CXX) -o overflow Overflow.cpp

composite1: Composite1.cpp
	$(CXX) -o composite1 Composite1.cpp

composite2: Composite2.cpp
	$(CXX) -o composite2 Composite2.cpp

scope1: Scope1.cpp
	$(CXX) -o scope1 Scope1.cpp

scope2: Scope2.cpp
	$(CXX) -o scope2 Scope2.cpp

extern: Extern_1.cpp Extern_2.cpp
	$(CXX) -o extern Extern_1.cpp Extern_2.cpp

clean:
	rm -f *.o wrong1 wrong2 wrong3 uninit datatypes1 datatypes2 overflow composite1 composite2 scope1 scope2
