CXX = g++
LIB = -lgtest_main -lgtest

seq: Seq.cpp
	$(CXX) -o seq Seq.cpp

if1: If1.cpp
	$(CXX) -o if1 If1.cpp

if2: If2.cpp
	$(CXX) -o if2 If2.cpp

if3: If3.cpp
	$(CXX) -o if3 If3.cpp

if4: If4.cpp
	$(CXX) -o if4 If4.cpp

if5: If5.cpp
	$(CXX) -o if5 If5.cpp

if6: If6.cpp
	$(CXX) -o if6 If6.cpp

loop1: Loop1.cpp
	$(CXX) -o loop1 Loop1.cpp

loop2: Loop2.cpp
	$(CXX) -o loop2 Loop2.cpp

loop3: Loop3.cpp
	$(CXX) -o loop3 Loop3.cpp

loop4: Loop4.cpp
	$(CXX) -o loop4 Loop4.cpp

cond1: Cond1.cpp
	$(CXX) -o cond1 Cond1.cpp

clean:
	rm -f *.o seq if[1-9] loop[1-9] cond[1-9]
