CXX = g++
LIB = -lgtest_main -lgtest

string1: String1.cpp
	$(CXX) -g -o string1 String1.cpp

string2: String2.cpp
	$(CXX) -g -o string2 String2.cpp

string3: String3.cpp
	$(CXX) -g -o string3 String3.cpp

string4: String4.cpp
	$(CXX) -g -o string4 String4.cpp

string5: String5.cpp
	$(CXX) -g -o string5 String5.cpp

clean:
	rm -f *.o string[1-9]
