CXX = g++
LIB = -lgtest_main -lgtest

swap: Swap.cpp
	$(CXX) -g -o swap Swap.cpp

pointer1: Pointer1.cpp
	$(CXX) -g -o pointer1 Pointer1.cpp

pointer2: Pointer2.cpp
	$(CXX) -g -o pointer2 Pointer2.cpp

pointer3: Pointer3.cpp
	$(CXX) -g -o pointer3 Pointer3.cpp

pointer4: Pointer4.cpp
	$(CXX) -g -o pointer4 Pointer4.cpp

pointer5: Pointer5.cpp
	$(CXX) -g -o pointer5 Pointer5.cpp

pointer6: Pointer6.cpp
	$(CXX) -g -o pointer6 Pointer6.cpp

clean:
	rm -f *.o swap pointer[1-9]
