CXX = g++
LIB = -lgtest_main -lgtest

fun1: Fun1.cpp
	$(CXX) -g -o fun1 Fun1.cpp

fun2: Fun2.cpp
	$(CXX) -g -o fun2 Fun2.cpp

fun3: Fun3.cpp
	$(CXX) -g -o fun3 Fun3.cpp

fun4: Fun4.cpp
	$(CXX) -g -o fun4 Fun4.cpp

fun5: Fun5.cpp
	$(CXX) -fpermissive -g -o fun5 Fun5.cpp

fun6: Fun6.cpp
	$(CXX) -fpermissive -g -o fun6 Fun6.cpp

fun7: Fun7.cpp
	$(CXX) -g -o fun7 Fun7.cpp

fun8: Fun8.cpp
	$(CXX) -fpermissive -g -o fun8 Fun8.cpp

fun9: Fun9.cpp
	$(CXX) -g -o fun9 Fun9.cpp

fun10: Fun10.cpp
	$(CXX) -g -o fun10 Fun10.cpp

clean:
	rm -f *.o fun[1-9] fun10
