CXX = g++
LIB = -lgtest_main -lgtest

array1: Array1.cpp
	$(CXX) -g -o array1 Array1.cpp

array2: Array2.cpp
	$(CXX) -g -o array2 Array2.cpp

array3: Array3.cpp
	$(CXX) -g -o array3 Array3.cpp

array4: Array4.cpp
	$(CXX) -g -o array4 Array4.cpp

array5: Array5.cpp
	$(CXX) -g -o array5 Array5.cpp

array6: Array6.cpp
	$(CXX) -g -o array6 Array6.cpp

clean:
	rm -f *.o array[1-9]
