CXX = g++
LIB = -lgtest_main -lgtest

array1: Array1.cpp
	$(CXX) -g -o array1 Array1.cpp

array2: Array2.cpp
	$(CXX) -g -o array2 Array2.cpp

array3: Array3.cpp
	$(CXX) -g -o array3 Array3.cpp

array4: Array4.cpp
	$(CXX) -g -o array4 Array4.cpp

array5: Array5.cpp
	$(CXX) -g -o array5 Array5.cpp

array6: Array6.cpp
	$(CXX) -g -o array6 Array6.cpp

array7: Array7.cpp
	$(CXX) -g -o array7 Array7.cpp

array8: Array8.cpp
	$(CXX) -g -o array8 Array8.cpp

array9: Array9.cpp
	$(CXX) -g -o array9 Array9.cpp

marray1: MArray1.cpp
	$(CXX) -g -o marray1 MArray1.cpp

marray2: MArray2.cpp
	$(CXX) -g -o marray2 MArray2.cpp

marray3: MArray3.cpp
	$(CXX) -g -o marray3 MArray3.cpp

marray4: MArray4.cpp
	$(CXX) -g -o marray4 MArray4.cpp

clean:
	rm -f *.o array[1-9] marray[1-9]
